version: '3.4'

services:
  netcoreloggerapp:
    image: ${DOCKER_REGISTRY-}netcorelogger
    ports:
        - "5000:5000"
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network   
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: elasticsearch  
    restart: always
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes:
        - esdata:/usr/share/elasticsearch/data
    environment:
        - discovery.type=single-node        
        - xpack.security.enabled=false
        - bootstrap.memory_lock=true  
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - app-network    
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    restart: always
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - app-network  
volumes:
    esdata:
        driver: local
networks:
  app-network:
    driver: bridge
